User.create!([
  {email: "cory@surrealweddingfilms.com", password: nil, password_digest: "$2a$10$dgfCdZIRYGEfOvurRHE/KuAAGWLVcLc.u.X0UeXgpUk3qBLoqvo22", company_name: "Surreal Wedding Films", stripe_publishable_key: nil, stripe_user_id: nil, stripe_refresh_token: nil, stripe_access_token: nil, website: nil, first_name: "Cory", last_name: "Williams"}
])

Couple.create!([
  {wedding_date: "2016-07-23", groom_first_name: "Michael", groom_last_name: "Dwyer", groom_email: "mdwyerjr@gmail.com", groom_phone: "", groom_location_gr: "", bride_first_name: "Christie", bride_last_name: "Richards", bride_email: "", bride_phone: "", bride_location_gr: "", planner_first_name: "", planner_last_name: "", planner_email: "", planner_phone: "", ceremony_address: "", reception_address: "", marital_address: "", user_id: 1},
  {wedding_date: "2016-10-08", groom_first_name: "Daniel", groom_last_name: "Gomez", groom_email: "", groom_phone: "(661) 431-9526", groom_location_gr: "Whispering Rose Ranch - Groom's Saloon", bride_first_name: "Hanah", bride_last_name: "Shaw", bride_email: "hanahshaw12@gmail.com", bride_phone: "(661) 342-8593", bride_location_gr: "Hotel Corque (Presidential Suite)", planner_first_name: "Vanessa", planner_last_name: "Vierra", planner_email: "", planner_phone: "", ceremony_address: "Whispering Rose Ranch", reception_address: "Whispering Rose Ranch", marital_address: "12351 Lene Place, Bakersfield, CA 93306", user_id: 1},
  {wedding_date: "2016-07-02", groom_first_name: "Rarig", groom_last_name: "Ross", groom_email: "", groom_phone: "(805) 757-3171", groom_location_gr: "Groom's House", bride_first_name: "Ellery", bride_last_name: "White", bride_email: "ewhitecollege@aol.com", bride_phone: "(805) 714-5011", bride_location_gr: "Firestone Vineyard - Big White House", planner_first_name: "Lovelyfest Events", planner_last_name: "", planner_email: "", planner_phone: "", ceremony_address: "Firestone Vineyard", reception_address: "Firestone Vineyard - Tasting Room", marital_address: "834 Fairway Vista Dr, Santa Maria, CA 93455", user_id: 1},
  {wedding_date: "2015-08-21", groom_first_name: "Eric", groom_last_name: "Hanson", groom_email: "ericrowellhanson@gmail.com", groom_phone: "(805) 886-7180", groom_location_gr: "Biltmore (Four Seasons), Santa Barbara, CA", bride_first_name: "Katie", bride_last_name: "Welch", bride_email: "", bride_phone: "(818) 312-0060", bride_location_gr: "Biltmore (Four Seasons), Santa Barbara, CA", planner_first_name: "Maren", planner_last_name: "Parsons", planner_email: "", planner_phone: "", ceremony_address: "Biltmore - Mariposa Garden, Santa Barbara, CA", reception_address: "Biltmore - El Mar, Santa Barbara, CA", marital_address: "22 W. Constance #3, Santa Barbara, CA", user_id: 1},
  {wedding_date: "2015-08-29", groom_first_name: "Samuel", groom_last_name: "Garelli", groom_email: "", groom_phone: "(805) 423-4588", groom_location_gr: "Vintage Ranch - House", bride_first_name: "Haley", bride_last_name: "Armstrong", bride_email: "hmarmstr@gmail.com", bride_phone: "(805) 591-9571", bride_location_gr: "Vintage Ranch - Cottage", planner_first_name: "Amanda", planner_last_name: "Landon", planner_email: "", planner_phone: "", ceremony_address: "Vintage Ranch - Oak Tree", reception_address: "Vintage Ranch - Barn", marital_address: "320 Abramson Rd. Templeton, CA 93465", user_id: 1},
  {wedding_date: "2015-09-19", groom_first_name: "Mike", groom_last_name: "Donabedian", groom_email: "mgdonabedian@gmail.com", groom_phone: "(805) 433-5824", groom_location_gr: "EZ1 Ranch", bride_first_name: "Gina", bride_last_name: "DelSanto", bride_email: "", bride_phone: "(818) 521-4134", bride_location_gr: "EZ1 Ranch", planner_first_name: "TBD", planner_last_name: "", planner_email: "", planner_phone: "", ceremony_address: "3730 Calf Canyon Highway, Creston, CA 93432", reception_address: "EZ1 Ranch & Vineyards", marital_address: "282 Virginia Drive, Newbury Park, CA 91320", user_id: 1},
  {wedding_date: "2015-11-07", groom_first_name: "Matthew", groom_last_name: "Ohlund", groom_email: "", groom_phone: "(650) 455-5170", groom_location_gr: "Groom's Hotel", bride_first_name: "Shelby", bride_last_name: "Borg", bride_email: "sborgcm@gmail.com", bride_phone: "(530) 906-4186", bride_location_gr: "Holland Ranch", planner_first_name: "", planner_last_name: "", planner_email: "", planner_phone: "", ceremony_address: "Holland Ranch, San Luis Obispo, CA", reception_address: "Holland Ranch, San Luis Obispo, CA", marital_address: "TBD", user_id: 1},
  {wedding_date: "2015-09-12", groom_first_name: "Brian", groom_last_name: "Moore", groom_email: "", groom_phone: "(714) 488-0542", groom_location_gr: "Groom's House", bride_first_name: "Brigitta", bride_last_name: "Olansky", bride_email: "brigitta.onlansky@gmail.com", bride_phone: "(714) 869 -8198", bride_location_gr: "1015 Debra Drive, Santa Barbara, CA", planner_first_name: "Carol", planner_last_name: "Borowitz", planner_email: "", planner_phone: "(805) 896-9544", ceremony_address: "Our Lady of Sorrows Catholic Church - 21 E Sola St, Santa Barbara, CA", reception_address: "Rincon Beach Club - 3805 Santa Claus Lane, Carpinteria, CA", marital_address: "1001 Seal Way #2, Seal Beach, CA 90740", user_id: 1},
  {wedding_date: "2015-11-15", groom_first_name: "Eric", groom_last_name: "Wittner", groom_email: "", groom_phone: "(510) 205-6539", groom_location_gr: "Grace Maralyn Estate - 14920 Round Mountain Heights, Atascadero, CA 93422", bride_first_name: "Amber", bride_last_name: "Brooks", bride_email: "aewittner@gmail.com", bride_phone: "(209) 985-7716", bride_location_gr: "Santa Margarita Ranch - Cottage", planner_first_name: "Mary", planner_last_name: "", planner_email: "joyfullyjoinedinto@gmail.com", planner_phone: "(805) 286-0688", ceremony_address: "Santa Margarita Ranch - Garden", reception_address: "Santa Margarita Ranch - Barn", marital_address: "249 Lake Almanor West Drive, Chester, CA 96020", user_id: 1},
  {wedding_date: "2016-04-30", groom_first_name: "Tyler", groom_last_name: "Kluender", groom_email: "", groom_phone: "(951) 553-5522", groom_location_gr: "The Barn", bride_first_name: "Chelsea", bride_last_name: "Belknapp", bride_email: "chelseabelknapp@gmail.com", bride_phone: "(408) 826-2177", bride_location_gr: "Hacienda De Leal", planner_first_name: "Roxanne", planner_last_name: "Belknapp", planner_email: "", planner_phone: "", ceremony_address: "The Barn Patio, Hollister, CA", reception_address: "Inside the Barn, Hollister, CA", marital_address: "5975 Desert Willow Dr, San Jose, CA 95123", user_id: 1},
  {wedding_date: "2015-05-16", groom_first_name: "Paul", groom_last_name: "Heintz", groom_email: "", groom_phone: "(937) 487-6814", groom_location_gr: "Orcutt Ranch", bride_first_name: "Becky", bride_last_name: "West", bride_email: "becks7399@yahoo.com", bride_phone: "(941) 726-0477", bride_location_gr: "Orcutt Ranch", planner_first_name: "TBD", planner_last_name: "", planner_email: "", planner_phone: "", ceremony_address: "Orcutt Ranch", reception_address: "Orcutt Ranch", marital_address: "1731 Huntington Dr. Unit D, South Pasadena, CA 91030", user_id: 1},
  {wedding_date: "2015-07-25", groom_first_name: "Farid", groom_last_name: "Kia", groom_email: "faridfkia@gmail.com", groom_phone: "(952) 210-1280", groom_location_gr: "The Cliffs Resort, Pismo Beach, CA", bride_first_name: "Parisa", bride_last_name: "Montazerolghaem", bride_email: "pmontazerolghaem@gmail.com", bride_phone: "(952) 250-0028", bride_location_gr: "The Cliffs Resort, Pismo Beach, CA", planner_first_name: "Anna", planner_last_name: "Fergus", planner_email: "", planner_phone: "", ceremony_address: "The Cliffs Resort, Pismo Beach, CA", reception_address: "The Cliffs Resort, Pismo Beach, CA", marital_address: "454 Stimson Ave, Pismo Beach, CA 93449", user_id: 1},
  {wedding_date: "2014-05-17", groom_first_name: "Jesse", groom_last_name: "Teniente", groom_email: "bteniente@gmail.com", groom_phone: "(805) 621-9009", groom_location_gr: "Groom's House", bride_first_name: "Melanie", bride_last_name: "Perez", bride_email: "melann15@hotmail.com", bride_phone: "(805) 478-2296", bride_location_gr: "831 Twilight Court, Santa Maria, CA", planner_first_name: "", planner_last_name: "", planner_email: "", planner_phone: "", ceremony_address: "Foster Road Kingdom Hall", reception_address: "9 Le Sage Drive, Grover Beach, CA 93433", marital_address: "831 Twilight Court, Santa Maria, CA", user_id: 1},
  {wedding_date: "2014-12-20", groom_first_name: "Gabriel", groom_last_name: "Loweree", groom_email: "", groom_phone: "(915) 861-2850", groom_location_gr: "Groom's House", bride_first_name: "Ashley", bride_last_name: "Hite", bride_email: "ashley.hite@myavemaria.edu", bride_phone: "(805) 550-0155", bride_location_gr: "Bride's House", planner_first_name: "TBD", planner_last_name: "", planner_email: "", planner_phone: "", ceremony_address: "Mission - San Luis Obispo, CA", reception_address: "Madonna Inn - Venetian Room", marital_address: "TBD", user_id: 1},
  {wedding_date: "2015-10-03", groom_first_name: "Justin", groom_last_name: "Pike", groom_email: "", groom_phone: "(240) 461-9317", groom_location_gr: "Hotel Corque, Solvang, CA", bride_first_name: "Corye", bride_last_name: "Goodman", bride_email: "corye.goodman@gmail.com", bride_phone: "(240) 461-9317", bride_location_gr: "Hotel Corque, Solvang, CA", planner_first_name: "TBD", planner_last_name: "", planner_email: "", planner_phone: "", ceremony_address: "Gainey Vineyard - Barn", reception_address: "Gainey Vineyard - Barn", marital_address: "2408 Penmar Avenue, Venice, CA 90291", user_id: 1},
  {wedding_date: "2015-09-26", groom_first_name: "Derek", groom_last_name: "Josephs", groom_email: "", groom_phone: "(914) 325-4971", groom_location_gr: "Rancho Valencia", bride_first_name: "Dani", bride_last_name: "Spear", bride_email: "cspear1@mac.com", bride_phone: "(917) 945-0498", bride_location_gr: "Rancho Santa Fe", planner_first_name: "Brooke", planner_last_name: "Keegan", planner_email: "", planner_phone: "", ceremony_address: "Rancho Valencia", reception_address: "Rancho Valencia", marital_address: "TBD", user_id: 1}
])

Event.create!([
  {title: "Michael and Christie", description: "", start_time: "2016-07-23 12:00:00", end_time: "2016-07-23 12:00:00", all_day: true, user_id: 1, couple_id: 1, event_type: "Wedding"},
  {title: "Daniel and Hanah", description: "Whispering Rose Ranch", start_time: "2016-10-08 12:00:00", end_time: "2016-10-08 12:00:00", all_day: true, user_id: 1, couple_id: 2, event_type: "Wedding"},
  {title: "Rarig and Ellery", description: "Firestone Vineyard", start_time: "2016-07-02 12:00:00", end_time: "2016-07-02 12:00:00", all_day: true, user_id: 1, couple_id: 3, event_type: "Wedding"},
  {title: "Eric and Katie", description: "Biltmore - Mariposa Garden, Santa Barbara, CA", start_time: "2015-08-21 12:00:00", end_time: "2015-08-21 12:00:00", all_day: true, user_id: 1, couple_id: 4, event_type: "Wedding"},
  {title: "Samuel and Haley", description: "Vintage Ranch - Oak Tree", start_time: "2015-08-29 00:00:00", end_time: "2015-08-29 00:00:00", all_day: true, user_id: 1, couple_id: 5, event_type: "Wedding"},
  {title: "Mike and Gina", description: "3730 Calf Canyon Highway, Creston, CA 93432", start_time: "2015-09-19 12:00:00", end_time: "2015-09-19 12:00:00", all_day: true, user_id: 1, couple_id: 6, event_type: "Wedding"},
  {title: "Matthew and Shelby", description: "Holland Ranch, San Luis Obispo, CA", start_time: "2015-11-07 12:00:00", end_time: "2015-11-07 12:00:00", all_day: true, user_id: 1, couple_id: 7, event_type: "Wedding"},
  {title: "Brian and Brigitta", description: "Our Lady of Sorrows Catholic Church - 21 E Sola St, Santa Barbara, CA", start_time: "2015-09-12 12:00:00", end_time: "2015-09-12 12:00:00", all_day: true, user_id: 1, couple_id: 8, event_type: "Wedding"},
  {title: "Eric and Amber", description: "Santa Margarita Ranch - Garden", start_time: "2015-11-15 12:00:00", end_time: "2015-11-15 12:00:00", all_day: true, user_id: 1, couple_id: 9, event_type: "Wedding"},
  {title: "Tyler and Chelsea", description: "The Barn Patio, Hollister, CA", start_time: "2016-04-30 12:00:00", end_time: "2016-04-30 12:00:00", all_day: true, user_id: 1, couple_id: 10, event_type: "Wedding"},
  {title: "Paul and Becky", description: "Orcutt Ranch", start_time: "2015-05-16 12:00:00", end_time: "2015-05-16 12:00:00", all_day: true, user_id: 1, couple_id: 11, event_type: "Wedding"},
  {title: "Farid and Parisa", description: "The Cliffs Resort, Pismo Beach, CA", start_time: "2015-07-25 12:00:00", end_time: "2015-07-25 12:00:00", all_day: true, user_id: 1, couple_id: 12, event_type: "Wedding"},
  {title: "Jesse and Melanie", description: "Foster Road Kingdom Hall", start_time: "2014-05-17 12:00:00", end_time: "2014-05-17 12:00:00", all_day: true, user_id: 1, couple_id: 13, event_type: "Wedding"},
  {title: "Gabriel and Ashley", description: "Mission - San Luis Obispo, CA", start_time: "2014-12-20 12:00:00", end_time: "2014-12-20 12:00:00", all_day: true, user_id: 1, couple_id: 14, event_type: "Wedding"},
  {title: "Justin and Corye", description: "Gainey Vineyard - Barn", start_time: "2015-10-03 12:00:00", end_time: "2015-10-03 12:00:00", all_day: true, user_id: 1, couple_id: 15, event_type: "Wedding"},
  {title: "Derek and Dani", description: "Rancho Valencia", start_time: "2015-09-26 12:00:00", end_time: "2015-09-26 12:00:00", all_day: true, user_id: 1, couple_id: 16, event_type: "Wedding"}
])