# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 756d920033f09882b438d0d3a980cadef06e2663ae82f282bca26ac0de66c8b730fec82a2d238192d6502bab3099bb7f7b1a78071adb525038e9e6f43bc81650

test:
  secret_key_base: 26c7aa74f6d10b4318eac6d392c4b078d0958e94a18a258ae7aff13f316470b723c1e6b3b7482059d4c36920e05acf6c9def51e39f2b387dd08bb8a4be3fd50c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
